AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk Web App with S3 Source Bundle, CI/CD Ready

Resources:
  myApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: "NodeJsApp"
      Description: AWS Elastic Beanstalk NodeJs Application

  myApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: myApplication
      Description: AWS ElasticBeanstalk NodeJs Application Version
      SourceBundle:
        S3Bucket: "elastic-beanstalk-lab-253775151832-eu-north-1-an" # TODO: Replace with parameter store key that references this value
        S3Key: nodejs-app.zip

  myConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: myApplication
      Description: AWS ElasticBeanstalk NodeJs Configuration Template
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: '1'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: '4'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref MyInstanceProfile        
      SolutionStackName: 64bit Amazon Linux 2023 running Node.js 20

  myEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: myApplication
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: myConfigurationTemplate
      VersionLabel:
        Ref: myApplicationVersion

  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref MyInstanceRole